version: "2.8"

services:
  vnc_recorder:
    build:
      context: goVNC
      dockerfile: Dockerfile
    ports:
      - 8090:8080
    volumes:
      - ./FBS:/app/FBS/
    environment:
      - OS_IDENTITYENDPOINT=${OS_IDENTITYENDPOINT}
      - OS_USERNAME=${OS_USERNAME}
      - OS_PASSWORD=${OS_PASSWORD}
      - OS_PROJECTID=${OS_PROJECTID}
      - OS_DOMAINID=${OS_DOMAINID}
      - OS_WSOCKHOST=${OS_WSOCKHOST}
      - MINIO_ENDPPOINT=${MINIO_ENDPPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    networks:
      - vnc_network

networks:
  vnc_network:
